spring:
  application:
    name: Lab_Camuda_08_JobWorker

server:
  port: 8999

camunda:
  client:
    mode: self-managed
    auth:
      client-id: zeebe
      client-secret: zecret
      issuer: http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token
    zeebe:
      enabled: true
      grpc-address: http://127.0.0.1:26500
      rest-address: http://127.0.0.1:8080
      audience: zeebe-api
      defaults:
        poll-interval: PT10S #Cau hinh 10s gui 1 lan cho toi khi het timeout se gui tiep. Request tiep theo dua vao timeout :
        stream-enabled: false
        request-timeout: 10S # Cau hinh request timeout (thoi gian xu ly co the bi anh huong boi toc do xu ly va do tre cua mang)P
        max-jobs-active: 5
        timeout: 1s # Thoi gian toi da ma job worker hoan thanh cong viec va phan hoi lai cho zeebe broker
#      base-url: ''
#      ca-certificate-path: ''
#      defaults:
#        auto-complete: false
#        enabled: false
#        fetch-variables: ''
#        force-fetch-all-variables: false
#        max-jobs-active: 3
#        max-retries: 3
#        method-info: 4
#        name: ''
#        poll-interval: 1
#        request-timeout: 1000
#        stream-enabled: false
#        stream-timeout: 3
#        tenant-ids: ''
#        timeout: 1000
#        type: ''
#      execution-threads: 1
#      keep-alive: 1
#      max-message-size: 1
#      max-metadata-size: 1
#      message-time-to-live: 1
#      override-authority: 1
#      prefer-rest-over-grpc: false
#      request-timeout: 1
#      scope: 1
#    identity:
#      scope: 1
#      enabled: false
#      base-url: ''
#      audience: ''


logging:
  level:
    root: OFF
    io:
      grpc: DEBUG
      camunda:
        zeebe:
          client: DEBUG

  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"